// app
export const SET_APP_VERSION = 'SET_APP_VERSION';
// locale
export const SET_LOCALE = 'SET_LOCALE';
// error
export const SHOW_ERROR = 'SHOW_ERROR';
export const ERROR = 'ERROR';
// success
export const SHOW_SUCCESS = 'SHOW_SUCCESS';
export const SUCCESS = 'SUCCESS';
// loading
export const SHOW_LOADING = 'SHOW_LOADING';
// auth
export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const SAVE_USER = 'SAVE_USER';
export const LOGOUT = 'LOGOUT';
export const EMAIL_VERIFIED = 'EMAIL_VERIFIED';
export const RESET_EMAIL_SENT = 'RESET_EMAIL_SENT';
export const SHOW_CHANGE_PASSWORD_INPUTS = 'SHOW_CHANGE_PASSWORD_INPUTS';
// profile
export const FILL_PROFILE = 'FILL_PROFILE';
export const ADD_PROFILE_DATA = 'ADD_PROFILE_DATA';
// categories
export const FILL_CATEGORIES = 'FILL_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const SAVE_A_SUBCATEGORIES = 'SAVE_A_SUBCATEGORIES';

// cities
export const FILL_ALL_CITIES = 'FILL_ALL_CITIES';
// Admin - Cities
export const CITIES = 'CITIES';
export const TOTAL_CITIES = 'TOTAL_CITIES';
// Admin - Users
export const USERS = 'USERS';
export const TOTAL_USERS = 'TOTAL_USERS';
// Wish - List
export const REMOVE_PRODUCT_FROM_WISH_LIST = 'REMOVE_PRODUCT_FROM_WISH_LIST';
export const ADD_PRODUCT_TO_WISH_LIST = 'ADD_PRODUCT_TO_WISH_LIST';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
// CART - List
export const REMOVE_PRODUCT_FROM_CART_LIST = 'REMOVE_PRODUCT_FROM_CART_LIST';
export const GET_A_PRODUCT = 'GET_A_PRODUCT';
export const ADD_PRODUCT_TO_CART_LIST = 'ADD_PRODUCT_TO_CART_LIST';
export const CLEAR_CART = 'CLEAR_CART';
export const INCREMENT_QUANTITY_CART = 'INCREMENT_QUANTITY_CART';
export const DECREMENT_QUANTITY_CART = 'DECREMENT_QUANTITY_CART';
export const CHECKOUT = 'CHECKOUT';

// Categories
export const SAVE_ALL_CATEGORIES = 'SAVE_ALL_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
//Products
export const SAVE_ALL_PRODUCTS = 'SAVE_ALL_PRODUCTS';
export const SAVE_ALL_PRODUCTS_VENDOR = 'SAVE_ALL_PRODUCTS_VENDOR';
export const SAVE_FILTERED_PRODUCTS = 'SAVE_FILTERED_PRODUCTS';
export const GET_RELATED_PRODUCT = 'GET_RELATED_PRODUCT';
//Messages
export const SAVE_ALL_MESSAGES = 'SAVE_ALL_MESSAGES';
export const FIND_A_MESSAGE = 'FIND_A_MESSAGE';
export const CREATE_A_MESSAGE = 'CREATE_A_MESSAGE';
export const INQUIRE_A_MESSAGE = 'INQUIRE_A_MESSAGE';
export const PUSH_A_MESSAGE = 'PUSH_A_MESSAGE';
//Search
export const SAVE_ALL_SEARCH_PRODUCTS = 'SAVE_ALL_SEARCH_PRODUCTS';
//Services
export const SAVE_ALL_SERVICES = 'SAVE_ALL_SERVICES';
export const SAVE_ALL_RETAILERS = 'SAVE_ALL_RETAILERS';
export const SAVE_ALL_SUPPLIERS = 'SAVE_ALL_SUPPLIERS';
export const SET_DELIVERY = 'SET_DELIVERY';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const SAVE_ALL_SUPPLIER_PRODUCTS = 'SAVE_ALL_SUPPLIER_PRODUCTS';
export const SAVE_ALL_FILTERED_PRODUCTS = 'SAVE_ALL_FILTERED_PRODUCTS';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';
export const SET_ORDER_HISTORY = 'SET_ORDER_HISTORY';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const SAVE_NEW_ARRIVAL = 'SAVE_NEW_ARRIVAL';
export const SAVE_BEST_PRODUCTS = 'SAVE_BEST_PRODUCTS';
export const CHECKOUT_CREATED = 'CHECKOUT_CREATED';
export const SET_VIS_FALSE = 'SET_VIS_FALSE';
export const SAVE_ALL_VENDOR_PRODUCTS = 'SAVE_ALL_VENDOR_PRODUCTS';
export const SAVE_ALL_VENDOR_INFO = 'SAVE_ALL_VENDOR_INFO';
export const SAVE_ALL_VENDOR_PRODUCTS_LOADING =
	'SAVE_ALL_VENDOR_PRODUCTS_LOADING';
export const CHANGE_TAB = 'CHANGE_TAB';
export const SET_CART_LIST = 'SET_CART_LIST';
export const CHANGE_RESET_PASSWORD = 'CHANGE_RESET_PASSWORD';
export const SET_DELIVERY_TYPES = 'SET_DELIVERY_TYPES';
export const CALCULATE_CART = 'CALCULATE_CART';
export const VERIFY_PAGE = 'VERIFY_PAGEd';
export const REQUEST_SENT = 'REQUEST_SENT';
export const SET_VERIFY = 'SET_VERIFY';
export const RITEM = 'RITEM';
export const addTCart = 'addTCart';
export const CLEAR_ALL_CART = 'CLEAR_ALL_CART';
//new
export const ADD_TO_PARENT_CATEGORY_PRODUCTS =
	'ADD_TO_PARENT_CATEGORY_PRODUCTS';
export const SET_CATEGORY_LOADING = 'SET_CATEGORY_LOADING';
export const ADD_TO_SUB_CATEGORY_PRODUCTS = 'ADD_TO_SUB_CATEGORY_PRODUCTS';
